/* tslint:disable */

/**
 * This file has been automatically generated by the [capnpc-ts utility](https://github.com/jdiaz5513/capnp-ts).
 */

import * as capnp from "capnp-ts";
import { ObjectSize as __O, Struct as __S, Interface as __I } from 'capnp-ts';
export const _capnpFileId = "a423f7a30021d311";
export class Param extends __S {
    static readonly _capnp = { displayName: "Param", id: "dbf6792701a335b4", size: new __O(0, 0) };
    toString(): string { return "Param_" + super.toString(); }
}
export class Result extends __S {
    static readonly _capnp = { displayName: "Result", id: "80adb3e95b185614", size: new __O(0, 0) };
    toString(): string { return "Result_" + super.toString(); }
}
